# 运行可以通过java -jar xxx.jar --spring.profiles.active={}方式去激活不同环境的配置
spring:
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: haier
    password: Haier
  #Zipkin配置
  zipkin:
    base-url: http://zipkin-server/
    locator:
      discovery:
        enabled: true
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      probability: 1.0

#sping boot admin 需要关闭此
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
